text="  this is the method text"
text2 =" "
print(text.lower())
print(text.upper())
print(text.title())
print(text.strip())
print(text.replace("method", "functionality"))
print(text.count("e"))
print(text.split())
print(text.startswith("  ")) 
print(text.endswith("!!")) 
print(text.find("method")) 
print(text.index("method")) 
print(text.capitalize())
print(text.center(120))
print(text.isalnum())
print(text.islower())
print(text.isupper())
print(text.isprintable())
print(text2.isspace())
print(text.swapcase())